shell /bin/zsh

cursor_trail 3
cursor_trail_decay 0.1 0.4

font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic

font_size 9

background_opacity 0.9
